[package]
name = "bugwiki"
version = "0.1.0"
authors = ["BrunoMunoz <ibruno.munoz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
csv = "1.1.3"
serde = "1.0.116"
serde_derive = "1.0.116"